# Generated by Django 2.2.2 on 2019-06-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.BigIntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('W', 'WEST'), ('E', 'EAST'), ('S', 'SOUTH'), ('N', 'NORTH'), ('CE', 'CENTRAL')], default='CE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='EXAMPLE_ID', max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
                ('ship_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.BigIntegerField(default=0)),
                ('state_name', models.CharField(default='state name', max_length=100)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount(%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.Customer')),
                ('product', models.ManyToManyField(to='minor_app.Product')),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Ship')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Segment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_app.State'),
        ),
    ]
