# Generated by Django 2.2.2 on 2019-06-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('WEST', 'WEST'), ('EAST', 'EAST'), ('SOUTH', 'SOUTH'), ('NORTH', 'NORTH'), ('CENTRAL', 'CENTRAL')], default='CE', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.SubCategory'),
        ),
    ]
