# Generated by Django 2.2.2 on 2019-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0002_auto_20190619_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_mode',
            field=models.CharField(choices=[('SeC', 'Second class'), ('StdC', 'Standard class'), ('FC', 'First Class'), ('Same', 'Same day')], max_length=8),
        ),
    ]
