# Generated by Django 2.2.2 on 2019-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0004_auto_20190621_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số lượng'),
        ),
    ]
