# Generated by Django 2.2.2 on 2019-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0005_auto_20190621_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_phone',
            field=models.CharField(default='0', max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_mode',
            field=models.CharField(choices=[('SeC', 'Second class'), ('StdC', 'Standard class'), ('FC', 'First Class'), ('Same', 'Same day')], max_length=8, verbose_name='Phương thức vận chuyển'),
        ),
    ]
