# Generated by Django 2.2.2 on 2019-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0006_auto_20190622_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, to='minor_app.Product', verbose_name='Sản phẩm'),
        ),
    ]
