# Generated by Django 2.2.2 on 2019-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0007_auto_20190622_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='minor_app.Product', verbose_name='Sản phẩm'),
        ),
    ]
