# Generated by Django 2.2.2 on 2019-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0009_auto_20190622_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_mode',
            field=models.CharField(choices=[('Second class', 'Second class'), ('Standard class', 'Standard class'), ('First Class', 'First Class'), ('Same day', 'Same day')], max_length=20, verbose_name='Phương thức vận chuyển'),
        ),
    ]
