# Generated by Django 2.2.2 on 2019-06-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0010_auto_20190622_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_app.Product')),
            ],
        ),
    ]
