# Generated by Django 2.2.2 on 2019-06-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_app', '0011_auto_20190624_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Giảm giá(%)'),
        ),
    ]
